### ISSUE TITLE
Something to be worried about?

### ISSUE THREAD

**Issue by krambriw** [bartbutenaers/node-red-contrib-msg-speed#7]
Hey Bart, when running "npm audit" I get the warnings below. Anything to be worried about? At least enough to be investigated I think? Using your latest 0.0.5

Best regards, Walter 

![image](https://user-images.githubusercontent.com/20238676/93706051-e7860000-fb22-11ea-9255-42e668cdf33e.png)
![image](https://user-images.githubusercontent.com/20238676/93706066-02587480-fb23-11ea-8bea-6143f76bd81b.png)

**Comment by bartbutenaers** [comment]
Hi Walter,
This has already been reported some time ago in this [issue](https://github.com/bartbutenaers/node-red-contrib-msg-speed/issues/5).
Will need to find some time to review this [feature ](https://github.com/bartbutenaers/node-red-contrib-msg-speed/issues/6) again, before I publish to NPM...
Bart

**Comment by bartbutenaers** [comment]
Hi Walter,
version ***1.0.0*** has been published, where this problem should be solved.
Kind regards,
Bart

**Comment by krambriw** [comment]
Thank you Bart! Works perfect, problem is solved!!
Best regards, Walter
